language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libev-dev
 - wget http://ftp.gnu.org/gnu/bison/bison-2.7.tar.gz && tar -zxf bison-2.7.tar.gz
 - pushd bison-2.7 && ./configure && sudo make all install && popd

script: ./autogen.sh && ./configure && make

compiler:
  - clang
  - gcc

notifications:
  email:
    - jonb@lanl.gov
