/** \file
 *  This C header file was generated by $ANTLR version 3.5
 *
 *     -  From the grammar source file : STOMP.g
 *     -                            On : 2013-01-28 11:02:03
 *     -                 for the lexer : STOMPLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
STOMPLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pSTOMPLexer, which is returned from a call to STOMPLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pSTOMPLexer are  as follows:
 *
 *  - 
 void
      pSTOMPLexer->T__11(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__12(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__13(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__14(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__15(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__16(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__17(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__18(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__19(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__20(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__21(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__22(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__23(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__24(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->T__25(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->NULL(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->LF(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->CR(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->EOL(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->COLON(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->OCTET(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->SPECIAL(pSTOMPLexer)
 *  - 
 void
      pSTOMPLexer->Tokens(pSTOMPLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_STOMPLexer_H
#define _STOMPLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct STOMPLexer_Ctx_struct STOMPLexer, * pSTOMPLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
STOMPLexer

 */
struct STOMPLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__11)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__12)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__13)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__14)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__15)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__16)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__17)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__18)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__19)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__20)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__21)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__22)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__23)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__24)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mT__25)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mNULL)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mLF)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mCR)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mEOL)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mCOLON)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mOCTET)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mSPECIAL)	(struct STOMPLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct STOMPLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct STOMPLexer_Ctx_struct * ctx);
    void	    (*free)   (struct STOMPLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pSTOMPLexer STOMPLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pSTOMPLexer STOMPLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__11      11
#define T__12      12
#define T__13      13
#define T__14      14
#define T__15      15
#define T__16      16
#define T__17      17
#define T__18      18
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define COLON      4
#define CR      5
#define EOL      6
#define LF      7
#define NULL      8
#define OCTET      9
#define SPECIAL      10
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for STOMPLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
