/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : STOMP.g
 *     -                            On : 2013-01-28 21:30:43
 *     -                 for the lexer : STOMPLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "STOMPLexer.h"
/* ----------------------------------------- */


/** String literals used by STOMPLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x41, 0x42, 0x4F, 0x52, 0x54,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x41, 0x43, 0x4B,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x42, 0x45, 0x47, 0x49, 0x4E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x43, 0x4F, 0x4D, 0x4D, 0x49, 0x54,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x43, 0x4F, 0x4E, 0x4E, 0x45, 0x43, 0x54,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x43, 0x4F, 0x4E, 0x4E, 0x45, 0x43, 0x54, 0x45, 0x44,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x44, 0x49, 0x53, 0x43, 0x4F, 0x4E, 0x4E, 0x45, 0x43, 0x54,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x45, 0x52, 0x52, 0x4F, 0x52,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x4D, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x4E, 0x41, 0x43, 0x4B,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x52, 0x45, 0x43, 0x45, 0x49, 0x50, 0x54,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x53, 0x45, 0x4E, 0x44,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x53, 0x54, 0x4F, 0x4D, 0x50,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_15[]  = { 0x55, 0x4E, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x42, 0x45,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pSTOMPLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pSTOMPLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pSTOMPLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pSTOMPLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__11    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__12    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__13    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__14    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__15    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__16    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__17    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__18    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__19    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__20    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__21    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__22    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__23    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__24    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mT__25    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mNULL    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mLF    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mCR    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mEOL    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mCOLON    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mOCTET    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mSPECIAL    (pSTOMPLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pSTOMPLexer ctx);
static void	STOMPLexerFree(pSTOMPLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
STOMPLexerFree  (pSTOMPLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
STOMPLexerReset (pSTOMPLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "STOMP.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called STOMPLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pSTOMPLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pSTOMPLexer STOMPLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return STOMPLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called STOMPLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pSTOMPLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pSTOMPLexer STOMPLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pSTOMPLexer ctx; // Context structure we will build and return

    ctx = (pSTOMPLexer) ANTLR3_CALLOC(1, sizeof(STOMPLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in STOMPLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our STOMPLexer interface
     */
    ctx->mT__11	= mT__11;
    ctx->mT__12	= mT__12;
    ctx->mT__13	= mT__13;
    ctx->mT__14	= mT__14;
    ctx->mT__15	= mT__15;
    ctx->mT__16	= mT__16;
    ctx->mT__17	= mT__17;
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mT__20	= mT__20;
    ctx->mT__21	= mT__21;
    ctx->mT__22	= mT__22;
    ctx->mT__23	= mT__23;
    ctx->mT__24	= mT__24;
    ctx->mT__25	= mT__25;
    ctx->mNULL	= mNULL;
    ctx->mLF	= mLF;
    ctx->mCR	= mCR;
    ctx->mEOL	= mEOL;
    ctx->mCOLON	= mCOLON;
    ctx->mOCTET	= mOCTET;
    ctx->mSPECIAL	= mSPECIAL;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= STOMPLexerFree;
    ctx->reset          = STOMPLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( 'ABORT' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__11
 *
 * Looks to match the characters the constitute the token T__11
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__11(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__11;


    // STOMP.g:7:7: ( 'ABORT' )
    // STOMP.g:7:9: 'ABORT'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleT__11Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__11Ex; /* Prevent compiler warnings */
    ruleT__11Ex: ;

}
// $ANTLR end T__11

//   Comes from: 8:7: ( 'ACK' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__12
 *
 * Looks to match the characters the constitute the token T__12
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__12(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__12;


    // STOMP.g:8:7: ( 'ACK' )
    // STOMP.g:8:9: 'ACK'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleT__12Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__12Ex; /* Prevent compiler warnings */
    ruleT__12Ex: ;

}
// $ANTLR end T__12

//   Comes from: 9:7: ( 'BEGIN' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__13
 *
 * Looks to match the characters the constitute the token T__13
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__13(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__13;


    // STOMP.g:9:7: ( 'BEGIN' )
    // STOMP.g:9:9: 'BEGIN'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleT__13Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__13Ex; /* Prevent compiler warnings */
    ruleT__13Ex: ;

}
// $ANTLR end T__13

//   Comes from: 10:7: ( 'COMMIT' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__14
 *
 * Looks to match the characters the constitute the token T__14
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__14(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__14;


    // STOMP.g:10:7: ( 'COMMIT' )
    // STOMP.g:10:9: 'COMMIT'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleT__14Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__14Ex; /* Prevent compiler warnings */
    ruleT__14Ex: ;

}
// $ANTLR end T__14

//   Comes from: 11:7: ( 'CONNECT' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__15
 *
 * Looks to match the characters the constitute the token T__15
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__15(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__15;


    // STOMP.g:11:7: ( 'CONNECT' )
    // STOMP.g:11:9: 'CONNECT'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleT__15Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__15Ex; /* Prevent compiler warnings */
    ruleT__15Ex: ;

}
// $ANTLR end T__15

//   Comes from: 12:7: ( 'CONNECTED' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__16
 *
 * Looks to match the characters the constitute the token T__16
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__16(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__16;


    // STOMP.g:12:7: ( 'CONNECTED' )
    // STOMP.g:12:9: 'CONNECTED'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleT__16Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__16Ex; /* Prevent compiler warnings */
    ruleT__16Ex: ;

}
// $ANTLR end T__16

//   Comes from: 13:7: ( 'DISCONNECT' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__17
 *
 * Looks to match the characters the constitute the token T__17
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__17(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__17;


    // STOMP.g:13:7: ( 'DISCONNECT' )
    // STOMP.g:13:9: 'DISCONNECT'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleT__17Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__17Ex; /* Prevent compiler warnings */
    ruleT__17Ex: ;

}
// $ANTLR end T__17

//   Comes from: 14:7: ( 'ERROR' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;


    // STOMP.g:14:7: ( 'ERROR' )
    // STOMP.g:14:9: 'ERROR'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 15:7: ( 'MESSAGE' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;


    // STOMP.g:15:7: ( 'MESSAGE' )
    // STOMP.g:15:9: 'MESSAGE'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 16:7: ( 'NACK' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__20
 *
 * Looks to match the characters the constitute the token T__20
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__20(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__20;


    // STOMP.g:16:7: ( 'NACK' )
    // STOMP.g:16:9: 'NACK'
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleT__20Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__20Ex; /* Prevent compiler warnings */
    ruleT__20Ex: ;

}
// $ANTLR end T__20

//   Comes from: 17:7: ( 'RECEIPT' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__21
 *
 * Looks to match the characters the constitute the token T__21
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__21(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__21;


    // STOMP.g:17:7: ( 'RECEIPT' )
    // STOMP.g:17:9: 'RECEIPT'
    {
        MATCHS(lit_11);
        if  (HASEXCEPTION())
        {
            goto ruleT__21Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__21Ex; /* Prevent compiler warnings */
    ruleT__21Ex: ;

}
// $ANTLR end T__21

//   Comes from: 18:7: ( 'SEND' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__22
 *
 * Looks to match the characters the constitute the token T__22
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__22(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__22;


    // STOMP.g:18:7: ( 'SEND' )
    // STOMP.g:18:9: 'SEND'
    {
        MATCHS(lit_12);
        if  (HASEXCEPTION())
        {
            goto ruleT__22Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__22Ex; /* Prevent compiler warnings */
    ruleT__22Ex: ;

}
// $ANTLR end T__22

//   Comes from: 19:7: ( 'STOMP' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__23
 *
 * Looks to match the characters the constitute the token T__23
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__23(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__23;


    // STOMP.g:19:7: ( 'STOMP' )
    // STOMP.g:19:9: 'STOMP'
    {
        MATCHS(lit_13);
        if  (HASEXCEPTION())
        {
            goto ruleT__23Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__23Ex; /* Prevent compiler warnings */
    ruleT__23Ex: ;

}
// $ANTLR end T__23

//   Comes from: 20:7: ( 'SUBSCRIBE' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__24;


    // STOMP.g:20:7: ( 'SUBSCRIBE' )
    // STOMP.g:20:9: 'SUBSCRIBE'
    {
        MATCHS(lit_14);
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 21:7: ( 'UNSUBSCRIBE' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__25;


    // STOMP.g:21:7: ( 'UNSUBSCRIBE' )
    // STOMP.g:21:9: 'UNSUBSCRIBE'
    {
        MATCHS(lit_15);
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 53:9: ( '\\u0000' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NULL
 *
 * Looks to match the characters the constitute the token NULL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNULL(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NULL;


    // STOMP.g:53:9: ( '\\u0000' )
    // STOMP.g:53:11: '\\u0000'
    {
        MATCHC(0x0000);
        if  (HASEXCEPTION())
        {
            goto ruleNULLEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNULLEx; /* Prevent compiler warnings */
    ruleNULLEx: ;

}
// $ANTLR end NULL

//   Comes from: 54:9: ( '\\u000A' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LF
 *
 * Looks to match the characters the constitute the token LF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLF(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LF;


    // STOMP.g:54:9: ( '\\u000A' )
    // STOMP.g:54:11: '\\u000A'
    {
        MATCHC(0x000A);
        if  (HASEXCEPTION())
        {
            goto ruleLFEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLFEx; /* Prevent compiler warnings */
    ruleLFEx: ;

}
// $ANTLR end LF

//   Comes from: 55:9: ( '\\u000D' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CR
 *
 * Looks to match the characters the constitute the token CR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCR(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CR;


    // STOMP.g:55:9: ( '\\u000D' )
    // STOMP.g:55:11: '\\u000D'
    {
        MATCHC(0x000D);
        if  (HASEXCEPTION())
        {
            goto ruleCREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCREx; /* Prevent compiler warnings */
    ruleCREx: ;

}
// $ANTLR end CR

//   Comes from: 56:9: ( ( CR )? LF )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EOL
 *
 * Looks to match the characters the constitute the token EOL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEOL(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EOL;


    // STOMP.g:56:9: ( ( CR )? LF )
    // STOMP.g:56:11: ( CR )? LF
    {
        // STOMP.g:56:11: ( CR )?
        {
            int alt1=2;
            switch ( LA(1) )
            {
                case '\r':
                	{
                		alt1=1;
                	}
                    break;
            }

            switch (alt1)
            {
        	case 1:
        	    // STOMP.g:
        	    {
        	        if ( LA(1) == '\r' )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleEOLEx;
        	        }


        	    }
        	    break;

            }
        }

        /* 56:11: ( CR )? LF */
        mLF(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleEOLEx;
        }



    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEOLEx; /* Prevent compiler warnings */
    ruleEOLEx: ;

}
// $ANTLR end EOL

//   Comes from: 57:9: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COLON
 *
 * Looks to match the characters the constitute the token COLON
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOLON(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COLON;


    // STOMP.g:57:9: ( ':' )
    // STOMP.g:57:11: ':'
    {
        MATCHC(':');
        if  (HASEXCEPTION())
        {
            goto ruleCOLONEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOLONEx; /* Prevent compiler warnings */
    ruleCOLONEx: ;

}
// $ANTLR end COLON

//   Comes from: 58:9: ( '\\u0000' .. '\\u00FF' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OCTET
 *
 * Looks to match the characters the constitute the token OCTET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOCTET(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OCTET;


    // STOMP.g:58:9: ( '\\u0000' .. '\\u00FF' )
    // STOMP.g:
    {
        if ( ((LA(1) >= 0x0000) && (LA(1) <= 0x00FF)) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleOCTETEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOCTETEx; /* Prevent compiler warnings */
    ruleOCTETEx: ;

}
// $ANTLR end OCTET

//   Comes from: 59:9: (~ ( LF | CR | COLON ) | OCTET )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SPECIAL
 *
 * Looks to match the characters the constitute the token SPECIAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSPECIAL(pSTOMPLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = SPECIAL;


    // STOMP.g:59:9: (~ ( LF | CR | COLON ) | OCTET )
    // STOMP.g:
    {
        if ( ((LA(1) >= 0x0000) && (LA(1) <= 0x00FF)) || ((LA(1) >= 0x000E) && (LA(1) <= '9')) || ((LA(1) >= ';') && (LA(1) <= 0xFFFF)) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleSPECIALEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSPECIALEx; /* Prevent compiler warnings */
    ruleSPECIALEx: ;

}
// $ANTLR end SPECIAL

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pSTOMPLexer ctx)
{
    {
        //  STOMP.g:1:8: ( T__11 | T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | NULL | LF | CR | EOL | COLON | OCTET | SPECIAL )

        ANTLR3_UINT32 alt2;

        alt2=22;

        {
            int LA2_0 = LA(1);
            if ( (LA2_0 == 'A'))
            {
                switch ( LA(2) )
                {
                case 'B':
                	{
                		alt2=1;
                	}
                    break;
                case 'C':
                	{
                		alt2=2;
                	}
                    break;

                default:
                    alt2=21;
                }

            }
            else if ( (LA2_0 == 'B'))
            {
                switch ( LA(2) )
                {
                case 'E':
                	{
                		alt2=3;
                	}
                    break;

                default:
                    alt2=21;
                }

            }
            else if ( (LA2_0 == 'C'))
            {
                switch ( LA(2) )
                {
                case 'O':
                	{
                		switch ( LA(3) )
                		{
                		case 'M':
                			{
                				alt2=4;
                			}
                		    break;
                		case 'N':
                			{
                				switch ( LA(4) )
                				{
                				case 'N':
                					{
                						switch ( LA(5) )
                						{
                						case 'E':
                							{
                								switch ( LA(6) )
                								{
                								case 'C':
                									{
                										switch ( LA(7) )
                										{
                										case 'T':
                											{
                												switch ( LA(8) )
                												{
                												case 'E':
                													{
                														alt2=6;
                													}
                												    break;

                												default:
                												    alt2=5;
                												}

                											}
                										    break;

                										default:
                										    CONSTRUCTEX();
                										    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                										    EXCEPTION->message      = (void *)"";
                										    EXCEPTION->decisionNum  = 2;
                										    EXCEPTION->state        = 40;


                										    goto ruleTokensEx;

                										}

                									}
                								    break;

                								default:
                								    CONSTRUCTEX();
                								    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                								    EXCEPTION->message      = (void *)"";
                								    EXCEPTION->decisionNum  = 2;
                								    EXCEPTION->state        = 39;


                								    goto ruleTokensEx;

                								}

                							}
                						    break;

                						default:
                						    CONSTRUCTEX();
                						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                						    EXCEPTION->message      = (void *)"";
                						    EXCEPTION->decisionNum  = 2;
                						    EXCEPTION->state        = 38;


                						    goto ruleTokensEx;

                						}

                					}
                				    break;

                				default:
                				    CONSTRUCTEX();
                				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                				    EXCEPTION->message      = (void *)"";
                				    EXCEPTION->decisionNum  = 2;
                				    EXCEPTION->state        = 37;


                				    goto ruleTokensEx;

                				}

                			}
                		    break;

                		default:
                		    CONSTRUCTEX();
                		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                		    EXCEPTION->message      = (void *)"";
                		    EXCEPTION->decisionNum  = 2;
                		    EXCEPTION->state        = 21;


                		    goto ruleTokensEx;

                		}

                	}
                    break;

                default:
                    alt2=21;
                }

            }
            else if ( (LA2_0 == 'D'))
            {
                switch ( LA(2) )
                {
                case 'I':
                	{
                		alt2=7;
                	}
                    break;

                default:
                    alt2=21;
                }

            }
            else if ( (LA2_0 == 'E'))
            {
                switch ( LA(2) )
                {
                case 'R':
                	{
                		alt2=8;
                	}
                    break;

                default:
                    alt2=21;
                }

            }
            else if ( (LA2_0 == 'M'))
            {
                switch ( LA(2) )
                {
                case 'E':
                	{
                		alt2=9;
                	}
                    break;

                default:
                    alt2=21;
                }

            }
            else if ( (LA2_0 == 'N'))
            {
                switch ( LA(2) )
                {
                case 'A':
                	{
                		alt2=10;
                	}
                    break;

                default:
                    alt2=21;
                }

            }
            else if ( (LA2_0 == 'R'))
            {
                switch ( LA(2) )
                {
                case 'E':
                	{
                		alt2=11;
                	}
                    break;

                default:
                    alt2=21;
                }

            }
            else if ( (LA2_0 == 'S'))
            {
                switch ( LA(2) )
                {
                case 'E':
                	{
                		alt2=12;
                	}
                    break;
                case 'T':
                	{
                		alt2=13;
                	}
                    break;
                case 'U':
                	{
                		alt2=14;
                	}
                    break;

                default:
                    alt2=21;
                }

            }
            else if ( (LA2_0 == 'U'))
            {
                switch ( LA(2) )
                {
                case 'N':
                	{
                		alt2=15;
                	}
                    break;

                default:
                    alt2=21;
                }

            }
            else if ( (LA2_0 == 0x0000))
            {
                alt2=16;
            }
            else if ( (LA2_0 == '\n'))
            {
                alt2=17;
            }
            else if ( (LA2_0 == '\r'))
            {
                switch ( LA(2) )
                {
                case '\n':
                	{
                		alt2=19;
                	}
                    break;

                default:
                    alt2=18;
                }

            }
            else if ( (LA2_0 == ':'))
            {
                alt2=20;
            }
            else if ( (((LA2_0 >= 0x0001) && (LA2_0 <= '\t')) || ((LA2_0 >= 0x000B) && (LA2_0 <= '\f')) || ((LA2_0 >= 0x000E) && (LA2_0 <= '9')) || ((LA2_0 >= ';') && (LA2_0 <= '@')) || ((LA2_0 >= 'F') && (LA2_0 <= 'L')) || ((LA2_0 >= 'O') && (LA2_0 <= 'Q')) || LA2_0 == 'T' || ((LA2_0 >= 'V') && (LA2_0 <= 0x00FF))))
            {
                alt2=21;
            }
            else if ( (((LA2_0 >= 0x0100) && (LA2_0 <= 0xFFFF))))
            {
                alt2=22;
            }
            else
            {

                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto ruleTokensEx;

            }
        }
        switch (alt2)
        {
    	case 1:
    	    // STOMP.g:1:10: T__11
    	    {
    	        /* 1:10: T__11 */
    	        mT__11(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // STOMP.g:1:16: T__12
    	    {
    	        /* 1:16: T__12 */
    	        mT__12(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // STOMP.g:1:22: T__13
    	    {
    	        /* 1:22: T__13 */
    	        mT__13(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // STOMP.g:1:28: T__14
    	    {
    	        /* 1:28: T__14 */
    	        mT__14(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // STOMP.g:1:34: T__15
    	    {
    	        /* 1:34: T__15 */
    	        mT__15(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // STOMP.g:1:40: T__16
    	    {
    	        /* 1:40: T__16 */
    	        mT__16(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // STOMP.g:1:46: T__17
    	    {
    	        /* 1:46: T__17 */
    	        mT__17(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // STOMP.g:1:52: T__18
    	    {
    	        /* 1:52: T__18 */
    	        mT__18(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // STOMP.g:1:58: T__19
    	    {
    	        /* 1:58: T__19 */
    	        mT__19(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // STOMP.g:1:64: T__20
    	    {
    	        /* 1:64: T__20 */
    	        mT__20(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // STOMP.g:1:70: T__21
    	    {
    	        /* 1:70: T__21 */
    	        mT__21(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // STOMP.g:1:76: T__22
    	    {
    	        /* 1:76: T__22 */
    	        mT__22(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // STOMP.g:1:82: T__23
    	    {
    	        /* 1:82: T__23 */
    	        mT__23(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // STOMP.g:1:88: T__24
    	    {
    	        /* 1:88: T__24 */
    	        mT__24(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // STOMP.g:1:94: T__25
    	    {
    	        /* 1:94: T__25 */
    	        mT__25(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // STOMP.g:1:100: NULL
    	    {
    	        /* 1:100: NULL */
    	        mNULL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // STOMP.g:1:105: LF
    	    {
    	        /* 1:105: LF */
    	        mLF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // STOMP.g:1:108: CR
    	    {
    	        /* 1:108: CR */
    	        mCR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // STOMP.g:1:111: EOL
    	    {
    	        /* 1:111: EOL */
    	        mEOL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // STOMP.g:1:115: COLON
    	    {
    	        /* 1:115: COLON */
    	        mCOLON(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // STOMP.g:1:121: OCTET
    	    {
    	        /* 1:121: OCTET */
    	        mOCTET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // STOMP.g:1:127: SPECIAL
    	    {
    	        /* 1:127: SPECIAL */
    	        mSPECIAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
